# Site settings
baseurl = "/web-syna/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Origoss Solutions"
theme = "syna"
enableGitInfo = true
version = "0.17.2"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
ignorefiles = [ "content/dev/.*" ]

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Origoss Solutions Ltd."
  description = "Open Source Theme for your next project"
  debug = true
  unsafeEvents = true # Default is false. Enables ?event=type format of url events.

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = "https://use.example.net"
    #id = ""
    #domain = "*" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#254f24"
    secondary = "#3fab3c"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#e0e0e0"
    danger = "#dc1200"
    light = "#ffffff"
    dark = "#000000"

# main/prepend/postpend menus are displayed in nav fragment.
# footer/footer_social menus are displayed in footer fragment.
# copyright_footer menus are displayed in copyright fragment
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/services"
  name = "Services"
  weight = 20

[[menu.main]]
  url = "/fragments"
  name = "Fragments"
  weight = 30

[[menu.main]]
  url = "/docs"
  name = "Docs"
  weight = 40

[[menu.main]]
  url = "/about"
  name = "About us"
  weight = 50

[[menu.main]]
  url = "/contact"
  name = "Contact us"
  weight = 50

[[menu.footer]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.footer]]
  url = "/services"
  name = "Services"
  weight = 20

[[menu.footer]]
  url = "/about"
  name = "About us"
  weight = 30

[[menu.footer]]
  url = "/contact"
  name = "Contact us"
  weight = 40

#[[menu.footer_social]]
#  weight = 30
#  name = "github"
#  url = "https://git.okkur.org/syna"
#  pre = "fab fa-github fa-stack-2x"

[[menu.copyright_footer]]
  url = "/about"
  name = "About us"
  weight = 10
