# Site settings
baseurl = "/web-syna/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Origoss Solutions"
theme = "syna"
enableGitInfo = true
version = "1.0"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Origoss Solutions Ltd."
  description = "Open Source Theme for your next project"
  debug = true
#  unsafeEvents = true # Default is false. Enables ?event=type format of url events.

  [params.style]
    background = "light"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = "https://use.example.net"
    #id = ""
    #domain = "*" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#254f24"
    secondary = "#3fab3c"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#e0e0e0"
    danger = "#dc1200"
    light = "#ffffff"
    dark = "#303030"

# main/prepend/postpend menus are displayed in nav fragment.
# footer/footer_social menus are displayed in footer fragment.
# copyright_footer menus are displayed in copyright fragment
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/services"
  name = "Services"
  weight = 20

[[menu.main]]
  url = "/about"
  name = "About us"
  weight = 30

[[menu.main]]
  url = "/contact"
  name = "Contact us"
  weight = 40

[[menu.footer_social]]
  url = "https://www.facebook.com/origoss/"
  name = "facebook"
  weight = 10
  pre = "fab fa-facebook"

[[menu.footer_social]]
  url = "https://www.linkedin.com/company/origoss/"
  name = "linkedin"
  weight = 20
#  pre = "fa fa-linkedin"
  pre = "fas fa-twitter"

[[menu.footer_social]]
  url = "https://twitter.com/origoss_com"
  name = "twitter"
  weight = 30
  pre = "fa fa-twitter"

[[menu.footer_social]]
  url = "https://www.instagram.com/origoss.io/"
  name = "instagram"
  weight = 40
  pre = "fab fa-instagram"

[[menu.footer_social]]
  url = "https://github.com/origoss"
  name = "github"
  weight = 50
  pre = "fab fa-github fa-stack-2x"

[[menu.copyright_footer]]
  url = "https://www.facebook.com/origoss/"
  name = "facebook"
  weight = 10
  pre = "fab fa-facebook"

[[menu.copyright_footer]]
  url = "https://www.linkedin.com/company/origoss/"
  name = "linkedin"
  weight = 20
  pre = "fa fa-linkedin"

[[menu.copyright_footer]]
  url = "https://twitter.com/origoss_com"
  name = "twitter"
  weight = 30
  pre = "fab fa-twitter"

[[menu.copyright_footer]]
  url = "https://www.instagram.com/origoss.io/"
  name = "instagram"
  weight = 40
  pre = "fab fa-instagram"

[[menu.copyright_footer]]
  url = "https://github.com/origoss"
  name = "github"
  weight = 50
  pre = "fab fa-github fa-stack-2x"
